---
title: "Tugas TG Praktikum"
author: "Muthi'ah Iffa Karimah"
date: "2025-09-30"
output: html_document
---

```{r}
library(MASS)
set.seed(91)

n_daring <- 20
n_luring <- 20

mu_daring <- c(60, 55)
mu_luring <- c(65, 60)
Sigma <- matrix(c(200,50,50,180), 2)

data_daring <- mvrnorm(n_daring, mu = mu_daring, Sigma = Sigma)
data_luring <- mvrnorm(n_luring, mu = mu_luring, Sigma = Sigma)

dataset <- data.frame(
  Daring_Teori   = data_daring[,1],
  Daring_Praktik = data_daring[,2],
  Luring_Teori   = data_luring[,1],
  Luring_Praktik = data_luring[,2]
)

dataset

```

```{r}
# Memisahkan Data dari Populasi 1 dan 2
data_daring = dataset[,1:2]
data_luring = dataset[,3:4]
```

```{r}
# Menghitung vektor rataan dan matriks kovarians
xbar1 = apply(data_daring, 2, mean)
xbar1

xbar2 = apply(data_luring, 2, mean)
xbar2

cov_m1 = cov(data_daring)
cov_m1

cov_m2 = cov(data_luring)
cov_m2

n1 = nrow(data_daring)
n2 = nrow(data_luring)
```

```{r}
# S Gabungan
s_gab = ((n1-1)*cov_m1 + (n2-1)*cov_m2)/(n1+n2-2)
s_gab

# Uji T2 Hotelling Dua Populasi Sampel Berpasangan
library(Hotelling)
t2_homogen = hotelling.test(data_daring, data_luring, var.equal=TRUE)
t2_homogen
```

```{r}
# Selang Kepercayaan Simultan
T.ci = function(mu1, mu2, S_gab, n1, n2, avec=rep(1,length(mu1)), level=0.95){
  p = length(mu1)
  mu = mu1 - mu2
  cval = qf(level, p, n1+n2-p-1) * p * (n1+n2-2) / (n1+n2-p-1)
  zhat = crossprod(avec, mu)
  zvar = crossprod(avec, S_gab %*% avec) * (1/n1 + 1/n2)
  const = sqrt(cval * zvar)
  c(lower = zhat - const, upper = zhat + const)
}
```

```{r}
# Teori
T.ci(xbar1, xbar2, s_gab, n1, n2, avec=c(1,0), level=0.95)

# Praktik
T.ci(xbar1, xbar2, s_gab, n1, n2, avec=c(0,1), level=0.95)

```

```{r}
# Selang Kepercayaan Bonferroni
bon = function(mu1, mu2 ,S, n1, n2, alpha, k){
  p = length(mu1)
  mu = mu1 - mu2
  lower = mu[k] - sqrt((S[k,k]) *(1/n1+1/n2))* abs(qt(alpha/(2*p), df=n1+n2-2))
  upper = mu[k] + sqrt((S[k,k]) *(1/n1+1/n2))* abs(qt(alpha/(2*p), df=n1+n2-2))
  ci = c(lower = lower, upper = upper)
  names(ci)= c("lower","upper")
  ci
}
```

```{r}
# Teori
bon(xbar1, xbar2, s_gab, n1, n2, 0.05, 1)

# Praktik
bon(xbar1, xbar2, s_gab, n1, n2, 0.05, 2)

```

```{r}
# Perbandingan Dua Vektor Nilai Tengah Sampel Saling Bebas Ragam Sama
# Input data
library(MASS)
set.seed(91)

n1 = 20
n2 = 20
mu1 = c(60, 55)
mu2 = c(65, 60)
Sigma = matrix(c(200,50,50,180), 2)  # sama untuk dua populasi

data1 = mvrnorm(n1, mu = mu1, Sigma = Sigma)
data2 = mvrnorm(n2, mu = mu2, Sigma = Sigma)

```

```{r}
dataset1 = data.frame(
  Pop1_X1 = data1[,1],
  Pop1_X2 = data1[,2],
  Pop2_X1 = data2[,1],
  Pop2_X2 = data2[,2]
)
dataset1
```

```{r}
# Memisahkan data dari Populasi 1 dan 2
pop1 = dataset1[,1:2]
pop2 = dataset1[,3:4]

# Menghitung vektor rataan dan matriks kovarians
xbar1 = colMeans(pop1); xbar1
xbar2 = colMeans(pop2); xbar2

cov1 = cov(pop1); cov1
cov2 = cov(pop2); cov2

n1 = nrow(pop1)
n2 = nrow(pop2)
```

```{r}
# S Gabungan
s_gab = ((n1-1)*cov1 + (n2-1)*cov2)/(n1+n2-2)
s_gab

# Uji T2 Hotelling Dua Populasi Ragam Sama
library(Hotelling)
t2_homogen = hotelling.test(pop1, pop2, var.equal=TRUE)
t2_homogen
```

```{r}
# Selang Kepercayaan Simultan
T.ci = function(mu1, mu2, S_gab, n1, n2, avec=rep(1,length(mu1)), level=0.95){
  p = length(mu1)
  mu = mu1 - mu2
  cval = qf(level, p, n1+n2-p-1) * p * (n1+n2-2) / (n1+n2-p-1)
  zhat = crossprod(avec, mu)
  zvar = crossprod(avec, S_gab %*% avec) * (1/n1 + 1/n2)
  const = sqrt(cval * zvar)
  c(lower = zhat - const, upper = zhat + const)
}
```

```{r}
# X1
T.ci(xbar1, xbar2, s_gab, n1, n2, avec=c(1,0), level=0.95)

# X2
T.ci(xbar1, xbar2, s_gab, n1, n2, avec=c(0,1), level=0.95)

# Selang Kepercayaan Bonferroni
bon = function(mu1, mu2 ,S, n1, n2, alpha, k){
  p = length(mu1)
  mu = mu1 - mu2
  lower = mu[k] - sqrt((S[k,k]) *(1/n1+1/n2))* abs(qt(alpha/(2*p), df=n1+n2-2))
  upper = mu[k] + sqrt((S[k,k]) *(1/n1+1/n2))* abs(qt(alpha/(2*p), df=n1+n2-2))
  ci = c(lower = lower, upper = upper)
  names(ci)= c("lower","upper")
  ci
}
```

```{r}
# X1
bon(xbar1, xbar2, s_gab, n1, n2, 0.05, 1)

# X2
bon(xbar1, xbar2, s_gab, n1, n2, 0.05, 2)
```

```{r}
# Perbandingan Dua Vektor Nilai Tengah Sampel Saling Bebas Ragam Tidak Sama
# Input data
set.seed(91)

n1 = 20
n2 = 20   # samain jumlah sampel biar bisa digabung
mu1 = c(50, 55)
mu2 = c(60, 65)

Sigma1 = matrix(c(150,20,20,100), 2)   # beda
Sigma2 = matrix(c(250,80,80,220), 2)

data1 = mvrnorm(n1, mu = mu1, Sigma = Sigma1)
data2 = mvrnorm(n2, mu = mu2, Sigma = Sigma2)
```

```{r}
dataset2 = data.frame(
  Pop1_X1 = data1[,1],
  Pop1_X2 = data1[,2],
  Pop2_X1 = data2[,1],
  Pop2_X2 = data2[,2]
)
dataset2

```

```{r}
# Memisahkan data dari populasi 1 dan 2
pop1 = dataset2[,1:2]
pop2 = dataset2[,3:4]

# Menghitung vektor rataan dan matriks kovarians
xbar1 = colMeans(pop1); xbar1
xbar2 = colMeans(pop2); xbar2

cov1 = cov(pop1); cov1
cov2 = cov(pop2); cov2
```

```{r}
# Uji T2 Hotelling Dua Populasi Ragam Tidak Sama
t2_heterogen = hotelling.test(pop1, pop2, var.equal=FALSE)
t2_heterogen
```
